"""add events and subevents composite indexes

Revision ID: 798ccc43d065
Revises: c369e310433d
Create Date: 2026-05-11 20:46:35.347411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798ccc43d065'
down_revision = 'c369e310433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_user_start', ['user_id', 'start_time'], unique=False)

    with op.batch_alter_table('subevents', schema=None) as batch_op:
        batch_op.create_index('ix_subevents_event_start', ['event_id', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subevents', schema=None) as batch_op:
        batch_op.drop_index('ix_subevents_event_start')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_user_start')

    # ### end Alembic commands ###
