"""add event embedding table

Revision ID: 8d34948237ad
Revises: 9f0a1b2c3d4e
Create Date: 2026-06-23 09:51:14.496236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d34948237ad'
down_revision = '9f0a1b2c3d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_embedding',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###

    # FTS5 lexical index (sparse half of hybrid retrieval). Not autogenerated by
    # Alembic — search_index also creates it idempotently for the test DB, which
    # is built via db.create_all() rather than migrations.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS event_fts "
        "USING fts5(event_id UNINDEXED, text)"
    )


def downgrade():
    op.execute("DROP TABLE IF EXISTS event_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_embedding')
    # ### end Alembic commands ###
